### ISSUE TITLE
Setup ZooKeeper

### ISSUE THREAD

**Issue by nichhk** [Rice-Comp413-2016/RDFS#15]
basic acceptance test: have a C executable that can connect to ZooKeeper and create a ZNode

**Comment by prb2** [comment]
This is technically kind of done. Should we close this issue and make a new one for implementing the wrapper functions that we need?

**Comment by prb2** [comment]
ZKWrapper methods needed for heartbeat demo:
- create znode
- get znode
- get children
- add watcher

**Comment by nichhk** [comment]
@prb2 @Joe--Chen @ap35 I think we're basically done with this. Just need to write some tests!
