### ISSUE TITLE
Create a ZooKeeper C++ Client

### ISSUE THREAD

**Issue by nichhk** [Rice-Comp413-2016/RDFS#16]
We can either model it off this https://github.com/apache/mesos/blob/master/src/zookeeper/zookeeper.cpp
or statically link it in. In the case that we want to statically link it, we also need https://github.com/apache/mesos/tree/master/3rdparty/libprocess

**Comment by nichhk** [comment]
@prb2 @Joe--Chen @ap35 I think we're nearly done with this. Just need to add the tests.

@Vegetable26 @Swyrough We still need to add multioperations.

**Comment by prb2** [comment]
I'll start writing some tests as soon as I finish the queue stuff
