### ISSUE TITLE
Implement Queues for ZooKeeper

### ISSUE THREAD

**Issue by nichhk** [Rice-Comp413-2016/RDFS#34]

**Comment by prb2** [comment]
@nichhk @cburk, checkout the header file I just made for the queues implementation and let me know if you have any suggestions. I'll be implementing these later today.

https://github.com/Rice-Comp413-2016/RDFS/commit/4d5d58df0208228e4d0be0af26a0552ec6e03d95

**Comment by prb2** [comment]
**Status update**
Mostly done and tested: https://github.com/Rice-Comp413-2016/RDFS/pull/72

Awaiting small change to zk_lock (#73) before adding locking in the pop method. Once that's done, this can be closed.

**Comment by prb2** [comment]
Done, merged #72 into develop
