### ISSUE TITLE
Incorporate AddBlock, GetBlockInfo, and data persistence layer into Client-DataNode data streaming

### ISSUE THREAD

**Issue by jfking** [Rice-Comp413-2016/RDFS#41]
Reads and writes between the client and DataNode currently rely on dummy data to show correctness. We want the client requests to reflect actual blocks with actual data in them, and we want the DataNode's response to reflect the contents of those files as written at an earlier date. On that note, the DataNode should be able to persist data received from the Client on that DataNode's  local FS.

**Comment by Drazcmd** [comment]
I believe we're processing read requests now, looks like write requests still need work.

**Comment by pelmers** [comment]
#47
