### ISSUE TITLE
Periodically write DataNode statistics to ZooKeeper

### ISSUE THREAD

**Issue by nichhk** [Rice-Comp413-2016/RDFS#57]
In particular, the NameNode needs to know 1) the free disk space on a DataNode and 2) the current number of transmissions on a DataNode when selecting target DataNodes for replication.

**Comment by nichhk** [comment]
blocked by #58 and #59

**Comment by nichhk** [comment]
We probably want to use @ap35's timer for this.

**Comment by efrederic** [comment]
We should send stats (number of xmits, available disk space, etc) from the datanode to zookeeper every 3(?) seconds. The stats will be added to the existing DataNodePayload struct in zk_dn_client.h

DataNodePayload fields:
uint32_t ipcPort;
uint32_t xferPort;
uint64_t disk_bytes; //total space on disk
uint64_t free_bytes; //free space on disk
uint32_t xmits; //current number of xmits
