### ISSUE TITLE
Send datanode stats periodically to zookeeper

### ISSUE THREAD

**Issue by efrederic** [Rice-Comp413-2016/RDFS#78]
We should send stats (number of xmits, available disk space, etc) from the datanode to zookeeper every 3(?) seconds. The stats will be added to the existing DataNodePayload struct in zk_dn_client.h

DataNodePayload fields:
uint32_t ipcPort;
uint32_t xferPort;
uint64_t disk_bytes; //total space on disk
uint64_t free_bytes; //free space on disk
uint32_t xmits; //current number of xmits

**Comment by nichhk** [comment]
This issue is a more detailed version of #57

**Comment by efrederic** [comment]
Nich pointed out an issue already exists. The above info is moving to #57
