### ISSUE TITLE
Race condition from client thinking block is complete before namenode

### ISSUE THREAD

**Issue by pelmers** [Rice-Comp413-2016/RDFS#81]
The data transfer server may complete its final acknowledge before blockReceived returns because acknowledgements are returned on a separate thread.

Then the client thinks its data is complete so it will complete on the namenode, but there is a chance the namenode did not process blockReceived in time and will fail.

**Comment by pelmers** [comment]
just noticed #80, maybe these could be related?

**Comment by Vegetable26** [comment]
This issue is actually an issue with LeaseManager. See https://github.com/Rice-Comp413-2016/RDFS/pull/87
